require 'csv'
require 'fileutils'
require 'open-uri'

require 'colorize'
require 'mechanize'

task default: %w[all]

task :all => %w[import:openn]

namespace :import do

  task openn: %w[schoenberg galen]

  desc 'Import Selected items from the Schoenberg collection'
  task :schoenberg do
    output_path = 'records/penn/schoenberg'
    FileUtils.mkdir_p output_path

    ids = %W(189 196 235 286 293 294 295 296 299 311 312 322 37 38 387 388 398 399 40 400 403 404 405 407 408 409 410 412 414 417 425 426 427 434 435 436 441 444 447 45 455 456 459 460 464 467 469 486 489 49 495)

    ids.each do |id|
      url = "http://openn.library.upenn.edu/Data/0001/ljs#{id}/data/ljs#{id}_TEI.xml"
      puts "Fetching #{url}"
      document = Nokogiri::XML(open(url))

      puts "Writing #{output_path}/ljs#{id}.xml file"
      File.open("#{output_path}/ljs#{id}.xml", 'w') { |file| file.write(document) }
    end
  end

  desc "Import Syriac Palimpset Folio"
  task :galen do
    # Description: http://openn.library.upenn.edu/Data/0014/GalenSyriacPalimpsest/0_ReadMe.txt
    # Folio Index: http://openn.library.upenn.edu/Data/0014/GalenSyriacPalimpsest/Documents/Internal/FolioIndex.html

  end



end
