require 'csv'
require 'fileutils'
require 'open-uri'

require 'colorize'
require 'mechanize'

task default: %w[all]

task :all => %w[import:met]

def setup
  @agent = Mechanize.new
  FileUtils.mkdir_p 'records'
end

def cleanup
  FileUtils.rm_rf 'records'
end

def cache_remote(link)
  f = File.basename(URI.parse(link).path)
  unless File.file? f
    puts "Downloading file".yellow
    @agent.get(link).save
  else
    puts "File exits. Skipping".blue
  end
end

namespace :import do

  task :met do
    # setup
    # cache_remote('https://github.com/metmuseum/openaccess/blob/master/MetObjects.csv?raw=true')
    #
    # # crawl the search results
    # url = 'http://www.metmuseum.org/art/collection#!?department=3&showOnly=openaccess&perPage=100&sortBy=Relevance&sortOrder=asc&offset=0&pageSize=0'
    puts "Read the README.md file. Met Museum objects filtered out in SQL.".yellow
  end

  namespace :penn do
    desc 'Download the latest dataset from Penn Museum'
    task :download do

    end

    def fetch_images(url, irn)
      puts "Fetching image asset from #{url}"
      page = @agent.get url
      {
        thumb: page.search('#main-content img.img-responsive')[0]['src'],
        fullsize: ''
      }
    end

    desc 'Enhance the latest cached dataset from Penn Musuem (e.g. add image links)'
    task :enhance_neareast do
      setup
      puts "Reading Near East dataset"
      Dir.glob(['records/near_eastern-20170820.csv']).each do |dataset|
        puts "Reading from #{dataset}".green
        new_file = File.basename(dataset, '.csv')
        new_file += "-enhanced.csv"
        csv = CSV.open("records/#{new_file}", 'a+')
        data = CSV.read(dataset, { headers: true })
        data.headers << 'image'
        csv << data.headers

        data.each do |row|
          images = fetch_images(row["url"], row["emuIRN"])
          row["image"] = images[:thumb]
          csv << row
        end

        # FileUtils.rm("records/#{new_file}")

        csv.close
      end
    end

    desc 'Enhance the latest cached datasets from Penn Musuem (e.g. add image links)'
    task :enhance do
      setup
      prefixes = %w(egyptian near_eastern)

      Dir.glob(['records/egyptian*.csv', 'records/near_eastern*.csv']).each do |dataset|
        puts "Reading from #{dataset}".green
        new_file = File.basename(dataset, '.csv')
        new_file += "-enhanced.csv"
        csv = CSV.open("records/#{new_file}", 'wb')
        data = CSV.read(dataset, { headers: true })
        data.headers << 'image'
        csv << data.headers

        data.each do |row|
          images = fetch_images(row["url"], row["emuIRN"])
          row["image"] = images[:thumb]
          csv << row
        end

        # FileUtils.rm("records/#{new_file}")

        csv.close
      end
    end
  end

  task :download_penn do
    datasets = %w(egyptian-csv-latest near-eastern-csv-latest)
    setup

    datasets.each do |data|
        puts "Downloading #{data} Dataset".green
        cache_remote("http://www.penn.museum/collections/assets/data/#{data}.zip")
        `unzip #{data}.zip`
    end

  end

  task :test_csv do
    # egyptian = CSV.read('./records/egyptian-20170820.csv')

    Dir.glob('./egyptian-20170820.csv').each do |file|
      file = CSV.read(file)
    end
  end
end
